### ISSUE TITLE
Privacy consideration

### ISSUE THREAD

**Issue by golightlyb** [pyalot/webglstats-site#36]
I am developing a WebGL game, and I would like to contribute to collecting your (very useful!) data by including the stats script.

However, I feel that it is good practice to inform users about what data is being collected and shared. Where this happens on my website, this is my job to communicate.

This is mostly trivial: the purpose of the website is quite clear:

"The statistics on this site help WebGL developers make decisions about hardware capabilities."

Is that all the information collected by the script, including by the CDN (other than the standard sever logs)?

If so, it would be helpful to say somewhere on the page, in as many words, that "no personally identifiable information is collected".

Many thanks!

**Comment by pyalot** [comment]
There are three aspects to your question. 

The first aspect is if I collect personally identifiable information. The answer is, I don't know, maybe, probably, but maybe not, who really knows? The information collected is about the hardware and browser capabilities, and some sites argue that that information constitutes "identifiable" information, because it can be used for "fingerprinting". I don't use it for fingerprinting, and I don't track users, but maybe I could, or maybe I can't, so I wouldn't really know what to say in this instance.

The second aspect is what I write on the site, bears no relevance to where most of the statistics come from. Sure I can write that on my site, but the tracker is embedded in other sites, and I can't dictate to them what they have to inform their users about.

The third aspect is what other sites write. I can't force them to write anything. I could display something to the user because I'm executing JS in that sites context, however, many sites would take exception to me interrupting (and nagging) users about what I collect within their web experience. They'd drop the tracker immediately and I'd be left with virtually zero statistical information.

So I don't know how to address your question.

**Comment by golightlyb** [comment]
With regards to points two and three - these aren't your problem, you don't need to do anything here.

With regards to the first, I see your point. I've read the EU guidance and recent rulings and it is a case-by-case argument. Generally it's not personally identifiable (PI) information if you don't or can't process it in a way that you could combine it with other PI. There are legitimate reasons to collect IP addresses in server logs but if sharing that data with other people it is good practice to anonymise it, because e.g. if *I* know a user on my website has one IP address, you've now told me a list of websites that user has visited. If you are not sharing that data, the question is less *could you* process the data such that it becomes PI, but are you *actually* processing the data such that it becomes PI.

Law aside, lets consider best practice of informing the user, who might notice the script on a page, wonder how their information is used, and visit the webglstats website for more information.

Something like "Privacy: The information collected by WebGL Stats is not used to personally identify you."

This should be sufficient as long as you aren't doing further processing to tying anything fingerprintable to collected location/referrer information, and if you share the data that anyone you share the data with can't do this either. Either by anonymising the IP address or separating the location/referrer information. Fingerprinting *alone* isn't PI, you might do this to e.g. only count stats of first-time visitors.

Sorry if this is all a big boring and pedantic, but I think it's important!

**Comment by golightlyb** [comment]
I think this is worth bumping now that GDPR is here.

You could rely on "legitimate interests" or consent, and it would be up to the website embedding the stats to justify this or manage consent.

However it would be helpful in meeting legal obligations if you could say:

- exactly what data you collect
- how long you store the data for (even if that's "forever" - the requirement is "no longer than is necessary for the purposes for which it is being processed")
- anyone you share the data with
- that GDPR data subject's rights apply (objecting to processing, requesting deletion, etc.) and in what cases these rights are limited (e.g. unable to verify identity to delete a record)

**Comment by pyalot** [comment]
> However it would be helpful in meeting legal obligations if you could say:

GDPR does apply to entities conducting business with residents of the EU which handle private data. Webglstats does not "conduct business" and it does not handle private data.

> exactly what data you collect

http://cdn.webglstats.com/

> how long you store the data for

It's forever. That's the necessary requirement to process the data. But it's of no relevance because that's a GDPR invention, which does not apply.

> anyone you share the data with

Nobody, but that's of no relevance because the GDPR does not apply.

> that GDPR data subject's rights apply

They do not apply.

>  (objecting to processing, requesting deletion, etc.)

Good luck with that, since I have neither a login nor personal data, identifying yourself to me will be rather... difficult.

**Comment by pyalot** [comment]
Btw. the GDPR's scope:

> The following cases are not covered by the regulation
> 
> - Lawful interception, national security, military, police, justice
> - **Statistical and scientific analysis**
> - Deceased persons are subject to national legislation
> - There is a dedicated law on employer-employee relationships
> - Processing of personal data by a natural person in the course of a purely personal or household activity
>
> **Conversely, an entity or more precisely an "enterprise" has to be engaged in "economic activity" to be covered by the GDPR**.

[Wikipedia](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation#Restrictions)

**Comment by golightlyb** [comment]
Sorry, that's untrue.

Statistical and scientific analysis is an Article 9 exemption, which doesn't apply here anyway. Article 6, [Article 89](http://www.privacy-regulation.eu/en/article-89-safeguards-and-derogations-relating-to-processing-for-archiving-purposes-the-public-interest-scientific-or-hi-GDPR.htm), [Recital 156](http://www.privacy-regulation.eu/en/recital-156-GDPR.htm) and [Recital 159](http://www.privacy-regulation.eu/en/recital-159-GDPR.htm) are still relevant.

"Economic activity" is defined very broadly and would still apply.

I believe WebGL stats collects important information in the public interest. Unfortunately any website with visitors from the European Economic Area cannot currently lawfully contribute to the stats collection without a privacy notice providing the information defined in [Article 13](http://www.privacy-regulation.eu/en/article-13-information-to-be-provided-where-personal-data-are-collected-from-the-data-subject-GDPR.htm).

You don't seem interested in this so I'm not going to push the issue any further - please close the issue after your final comment.

**Comment by pyalot** [comment]
> "Economic activity" is defined very broadly and would still apply.

I derive no financial gain from webglstats. I have no economic relationship with any of the contributing sites, nor with any of the visitors, directly or indirectly. I cover all operating expenses out of my own pocket and display neither advertising, nor do I accept payment in any form (neither as donations, nor as compensation for services). I hold no customer contact of any kind. How the hell do you define that as "economic activity"?

**Comment by golightlyb** [comment]
Because its a term with a specific meaning under European case law?

**Comment by pyalot** [comment]
How do you define something as "economic activity" when no economic activity takes place?

**Comment by pyalot** [comment]
You seem to desperately want to apply the GDPR to me, which cannot apply because:

1. I don't engage in economic activity on webglstats.
2. I don't collect personal information
3. I'm doing it for statistical purposes which are specifically again excempt generally, except where personal data is concerned, which I do not collect.

Even if I wanted to associate anybody, I couldn't. If you provided me any details to produce records for, I couldn't, because I wouldn't know if those are your records. That so hard to understand?

**Comment by pyalot** [comment]
It's therefore of no relevance for any website within the EU if they use my data collector.

**Comment by pyalot** [comment]
You can clearly see the problem with a "law" if you interpret it to potentially apply to everybody on the world, yet you'd need to commission an applicability study involving a team of technical and legal experts in each individual example to figure out if it actually applies right?

**Comment by golightlyb** [comment]
This is going in circles. I'm muting the thread so please save yourself some time and leave it there.

**Comment by pyalot** [comment]
I find the whole thing offensive. The retard law the EU "passed" here is impractical to apply even if it does apply, which you don't know. It's Schrodinger's law essentially. That's no way to run a legislative. It's a way to look like a bunch of fucking retards.

**Comment by pyalot** [comment]
You know what fuck this shit. If you're going to give me a hard time here I'm just gonna shut the whole thing down and see how you get your WebGL information then. Alright?`

I put my own money and effort into this project and I'm fed up with the EUtards. You can stick where the sun don't shine and live without WebGL Stats.

**Comment by polarathene** [comment]
Not a lawyer(so obvious, none of this is legal advice), but my understanding is that @pyalot is correct in not having to be concerned.

Recital 23 addresses that a website that's clearly not targeting the EU is not within territorial scope(iirc this plays into Article 3.2 A and B). I looked into this thing a year or so ago myself and there seems to be a lot of misunderstandings about whom it applies to.

I also recall that a warning would be sent out if there was any actual violation and you'd receive some duration to handle it before further action(in the event such is possible to take). It's mostly for malicious actors and to keep certain businesses in check, especially those that do target EU users explicitly.

---

As for third-parties that add the js stats snippet to send the data, if they fall under GDPR or want to be compliant regardless, probably should mention it in the policy document/page. Different types of data can be opt-in/opt-out, but anyone who is concerned about such and implementing such a policy should know what to do or consult a professional that does, this snippet would likely be the least of their worries.

---

BTW, thanks for keeping webglstats running, your last comment isn't clear, I can see you were upset a fair bit, did you block EU IP range? I'm glad that you didn't pull the whole thing down because of subset of users causing you grief.

**Comment by golightlyb** [comment]
lol "grief" it was a single open issue by one person
